name: cassandra
dependencies:
  - jupyter==1.0.0
  - numpy==1.18.5
  - pandas==1.0.5
  - pip
  - pip:
      - -e .  # executes setup.py -> 'src' becomes a (local) package
      - cassandra-driver==3.24.0
      - pytest==6.2.1
      - python-dotenv==0.15.0
